# Generated by Django 6.0.4 on 2026-05-17 04:08

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('images', models.ImageField(upload_to=products.models.product_image_path, validators=[products.models.validate_img])),
                ('meta_data', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('camera_accessories', 'camera_accessories'), ('tv_video', 'tv_video'), ('computers_laptops', 'computers_laptops'), ('cooling_air_treatment', 'cooling_air_treatment'), ('home_appliances', 'home_appliances'), ('health_beauty_hair', 'health_beauty_hair'), ('books', 'books'), ('music', 'music'), ('home_lifestyle', 'home_lifestyle'), ('home_improvements_tools', 'home_improvements_tools'), ('women_style', 'women_style'), ('mens_style', 'mens_style'), ('watches_glasses', 'watches_glasses'), ('sports_outdoors', 'sports_outdoors'), ('entertainment', 'entertainment')], max_length=50, null=True)),
            ],
        ),
    ]
