# Generated by Django 6.0.4 on 2026-05-01 12:14

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import sell.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Info',
            fields=[
                ('seller_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('seller_verification', models.FileField(upload_to='seller/seller_verify', validators=[sell.models.validate_pdf])),
                ('address', models.TextField()),
                ('seller_qr', models.FileField(upload_to='seller/seller_qr')),
                ('upi_id', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid UPI ID (e.g., name@bank)', regex='^[a-zA-Z0-9.\\-_]{2,256}@[a-zA-Z]{2,64}$')])),
                ('seller_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
