# Generated by Django 6.0.4 on 2026-05-17 04:08

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import sell.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buy', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Info',
            fields=[
                ('seller_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('seller_first_name', models.CharField(default='NA', max_length=100)),
                ('seller_last_name', models.CharField(max_length=100)),
                ('seller_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('seller_verification', models.FileField(upload_to=sell.models.seller_verification_path, validators=[sell.models.validate_pdf])),
                ('address', models.TextField()),
                ('seller_qr', models.FileField(upload_to=sell.models.seller_qr_path, validators=[sell.models.validate_img])),
                ('upi_id', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid UPI ID (e.g., name@bank)', regex='^[a-zA-Z0-9.\\-_]{2,256}@[a-zA-Z]{2,64}$')])),
                ('sells_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('seller_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.buyer_info')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.orderproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.seller_info')),
            ],
        ),
    ]
