# Generated by Django 6.0.4 on 2026-05-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_info',
            name='seller_email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='seller_info',
            name='seller_username',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
