# Generated by Django 6.0.4 on 2026-05-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_info',
            old_name='seller_name',
            new_name='seller_last_name',
        ),
        migrations.AddField(
            model_name='seller_info',
            name='seller_first_name',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
