# Generated by Django 6.0.4 on 2026-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0002_seller_info_seller_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='seller_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
