# Generated by Django 6.0.4 on 2026-05-06 10:07

import django.db.models.deletion
import sell.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_remove_buyer_info_address_buyer_info_address_line1_and_more'),
        ('sell', '0002_rename_seller_name_seller_info_seller_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='seller_qr',
            field=models.FileField(upload_to=sell.models.seller_qr_path, validators=[sell.models.validate_img]),
        ),
        migrations.AlterField(
            model_name='seller_info',
            name='seller_verification',
            field=models.FileField(upload_to=sell.models.seller_verification_path, validators=[sell.models.validate_pdf]),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=15)),
                ('quantity', models.IntegerField()),
                ('images', models.ImageField(upload_to=sell.models.product_image_path, validators=[sell.models.validate_img])),
                ('meta_data', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'electronics'), ('camera_accessories', 'camera_accessories'), ('tv_video', 'tv_video'), ('computers_laptops', 'computers_laptops'), ('cooling_air_treatment', 'cooling_air_treatment'), ('home_appliances', 'home_appliances'), ('health_beauty_hair', 'health_beauty_hair'), ('books', 'books'), ('music', 'music'), ('home_lifestyle', 'home_lifestyle'), ('home_improvements_tools', 'home_improvements_tools'), ('women_style', 'women_style'), ('mens_style', 'mens_style'), ('watches_glasses', 'watches_glasses'), ('sports_outdoors', 'sports_outdoors'), ('entertainment', 'entertainment')], max_length=50, null=True)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.seller_info')),
            ],
        ),
        migrations.CreateModel(
            name='SellingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.buyer_info')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.orderproduct')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.product')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.seller_info')),
            ],
        ),
    ]
