# Generated by Django 6.0.4 on 2026-05-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0003_alter_seller_info_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='seller_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
