# Generated by Django 6.0.4 on 2026-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0004_alter_seller_info_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_info',
            name='seller_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
