# Generated by Django 6.0.4 on 2026-05-17 04:08

import buy.models
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('order_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('upi_id', 'upi_id'), ('credit/debit', 'credit/debit'), ('qr_code', 'qr_code'), ('cash_on_delivery', 'cash_on_delivery')], max_length=30)),
                ('payment_reference_id', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer_Info',
            fields=[
                ('buyer_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('buyer_first_name', models.CharField(max_length=70)),
                ('buyer_last_name', models.CharField(max_length=70)),
                ('buyer_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=buy.models.profile_pic_path)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(default=' ', max_length=70)),
                ('postal_code', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('buyer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.buyer_info')),
            ],
        ),
    ]
