# Generated by Django 6.0.4 on 2026-05-01 12:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_Info',
            fields=[
                ('buyer_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('buyer_first_name', models.CharField(max_length=70)),
                ('buyer_last_name', models.CharField(max_length=70)),
                ('buyer_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField()),
                ('buyer_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
