# Generated by Django 6.0.4 on 2026-05-06 10:07

import buy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer_info',
            name='address',
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='address_line1',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='address_line2',
            field=models.CharField(default=' ', max_length=250),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='city',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='country',
            field=models.CharField(default=' ', max_length=70),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='postal_code',
            field=models.DecimalField(decimal_places=0, blank=True, null=True, max_digits=20),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=buy.models.profile_pic_path),
        ),
        migrations.AddField(
            model_name='buyer_info',
            name='state',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('order_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('payment_mode', models.CharField(choices=[('upi_id', 'upi_id'), ('credit/debit', 'credit/debit'), ('qr_code', 'qr_code'), ('cash_on_delivery', 'cash_on_delivery')], max_length=30)),
                ('payment_reference_id', models.DecimalField(decimal_places=0, max_digits=10)),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.buyer_info')),
            ],
        ),
    ]
