# Generated by Django 6.0.4 on 2026-05-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_info',
            name='buyer_username',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
