# Generated by Django 6.0.4 on 2026-05-06 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0002_remove_buyer_info_address_buyer_info_address_line1_and_more'),
        ('sell', '0003_alter_seller_info_seller_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.product'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.seller_info'),
        ),
    ]
