# Generated by Django 6.0.4 on 2026-05-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_buyer_info_buyer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer_info',
            name='buyer_email_id',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
