# Generated by Django 6.0.4 on 2026-05-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0003_orderproduct_product_id_orderproduct_seller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_info',
            name='address_line1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='address_line2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='postal_code',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='buyer_info',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
