# Generated by Django 6.0.4 on 2026-05-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_buyer_info_buyer_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer_info',
            name='buyer_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
