# Generated by Django 6.0.4 on 2026-05-07 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0004_alter_buyer_info_address_line1_and_more'),
        ('sell', '0003_alter_seller_info_seller_qr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.buyer_info')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buy.orderproduct')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.product')),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.seller_info')),
            ],
        ),
    ]
