# Generated by Django 6.0 on 2026-01-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HospitalProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
