# Generated by Django 6.0 on 2026-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_userinfo_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=122)),
                ('registration_id', models.CharField(max_length=122)),
                ('city', models.CharField(max_length=60)),
                ('contact_number', models.BigIntegerField()),
                ('license', models.FileField(blank=True, null=True, upload_to='hospital_licenses/')),
                ('hospital_password', models.CharField(max_length=122)),
            ],
        ),
    ]
