# Generated by Django 6.0 on 2026-01-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_hospitalprofile_latitude_hospitalprofile_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='uer',
            new_name='user',
        ),
    ]
