# Generated by Django 6.0 on 2026-01-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_uer_hospitalprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=122)),
                ('aadhar_id', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('PNS', 'Prefer Not Say')], max_length=15, null=True)),
                ('city', models.CharField(max_length=60)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('weight', models.PositiveIntegerField()),
                ('medical_condition', models.CharField(blank=True, max_length=122, null=True)),
                ('doc_report', models.FileField(blank=True, null=True, upload_to='user_report/')),
            ],
        ),
        migrations.CreateModel(
            name='OrganDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=122)),
                ('aadhar_id', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('PNS', 'Prefer Not Say')], max_length=15, null=True)),
                ('city', models.CharField(max_length=60)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('aliveordec', models.CharField(choices=[('A', 'Alive'), ('D', 'Deceased')], max_length=10, null=True)),
                ('organ', models.CharField(choices=[('Kidney', 'Kidney'), ('Liver', 'Liver'), ('Lungs', 'Lungs'), ('Heart', 'Heart'), ('Pancreas', 'Pancreas'), ('Intestine', 'Intestine'), ('Uterus', 'Uterus'), ('Eyes', 'Eyes'), ('Tissues', 'Tissues')], max_length=20, null=True)),
                ('weight', models.PositiveIntegerField()),
                ('medical_condition', models.CharField(max_length=122)),
                ('doc_report', models.FileField(blank=True, null=True, upload_to='user_report/')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
