# Generated by Django 6.0 on 2026-01-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blooddonation_organdonation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='form_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='form_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
