# Generated by Django 6.0 on 2026-01-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_blooddonation_form_id_organdonation_form_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='form_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organdonation',
            name='form_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
