# Generated by Django 6.0 on 2026-01-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_bloodrequest_emergencybloodrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='abminusunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='abplusunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='aminusunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='aplusunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='bminusunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='bplusunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='ominusunit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='oplusunit',
            field=models.IntegerField(default=0),
        ),
    ]
