# Generated by Django 6.0 on 2026-01-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_hospitalprofile_abminusunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencybloodrequest',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='emergencyorganrequest',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='organdonation',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='organrequest',
            name='weight',
            field=models.FloatField(),
        ),
    ]
