# Generated by Django 6.0 on 2026-01-31 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_emergencybloodrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='bloodrequest',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='emergencybloodrequest',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='emergencyorganrequest',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='organdonation',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='organrequest',
            name='remarks',
        ),
    ]
