# Generated by Django 6.0 on 2026-02-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_blooddonation_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='news_content',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='news_title',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
