# Generated by Django 6.0 on 2026-02-06 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_hospitalprofile_news_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='news_content',
        ),
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='news_title',
        ),
        migrations.CreateModel(
            name='HospitalNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='home.hospitalprofile')),
            ],
        ),
    ]
