# Generated by Django 6.0 on 2026-02-08 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_hospitalprofile_news_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_blood_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyorganrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_organ_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organ_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
