# Generated by Django 6.0 on 2026-02-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_blooddonation_user_bloodrequest_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='appointment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='appointments/blood_donations/'),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='appointment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='appointments/blood_requests/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='appointment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='appointments/emergency_blood_requests/'),
        ),
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyorganrequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyorganrequest',
            name='appointment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='appointments/emergency_organ_requests/'),
        ),
        migrations.AddField(
            model_name='emergencyorganrequest',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='appointment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='appointments/organ_donations/'),
        ),
        migrations.AddField(
            model_name='organdonation',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='appointment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='appointments/organ_requests/'),
        ),
        migrations.AddField(
            model_name='organrequest',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
