# Generated by Django 6.0 on 2026-02-16 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_blooddonation_appointment_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='accepted_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_emergency_blood_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencybloodrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='emergencyorganrequest',
            name='accepted_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_emergency_organ_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyorganrequest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.emergencybloodrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to=settings.AUTH_USER_MODEL)),
                ('organ_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.emergencyorganrequest')),
            ],
        ),
    ]
